### ISSUE TITLE
Mehr github workflows

### ISSUE THREAD

**Issue by spamviech** [spamviech/zugkontrolle#71]
Release nach merge auf main erstellen
- https://dzfrias.dev/blog/deploy-rust-cross-platform-github-actions
- https://github.com/houseabsolute/actions-rust-cross

"CI": Build, clippy, tests ausführen
- https://github.com/actions-rs
- https://kerkour.com/rust-github-actions-ci-cd

**Comment by spamviech** [comment]
Release-Kommentar: deploy-Skript + Beispiel-`.journal` anpassen.
Alternativ: automatisch im `prepare_release.py`-Skript.

**Comment by spamviech** [comment]
Github-Vorschlag für rust:
```yaml
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

```
